services:
  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keiko_network
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev --http-port=8080
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-db
    networks:
      - keiko_network
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.infra.local`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.docker.network=keiko_network"

volumes:
  keycloak_db_data:

networks:
  keiko_network:
    external: true
