services:
  nifi:
    image: apache/nifi:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    ports:
      - "8443:8443"
    networks:
      - keiko_network
    volumes:
      - nifi_data:/opt/nifi/nifi-current
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_PROXY_CONTEXT_PATH=/nifi
      - SINGLE_USER_CREDENTIALS_USERNAME=keiko
      - SINGLE_USER_CREDENTIALS_PASSWORD=123456123456
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nifi.rule=Host(`nifi.infra.local`) && PathPrefix(`/nifi`)"
      - "traefik.http.routers.nifi.entrypoints=websecure"
      - "traefik.http.routers.nifi.tls=true"
      - "traefik.http.services.nifi.loadbalancer.server.port=8443"
      - "traefik.http.services.nifi.loadbalancer.server.scheme=https"
      - "traefik.docker.network=keiko_network"
volumes:
  nifi_data:

networks:
  keiko_network:
    external: true