services:
  nifi:
    image: apache/nifi:latest
    hostname: nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTP_HOST=0.0.0.0
    volumes:
      - nifi_data:/opt/nifi/nifi-current
    networks:
      - keiko_network
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nifi.rule=Host(`nifi.infra.local`)"
      - "traefik.http.routers.nifi.entrypoints=websecure"
      - "traefik.http.routers.nifi.tls=true"
      - "traefik.http.services.nifi.loadbalancer.server.port=8080"
      - "traefik.docker.network=keiko_network"

volumes:
  nifi_data:

networks:
  keiko_network:
    external: true