[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"

  [entryPoints.websecure]
    address = ":443"

  # TCP para SMTP STARTTLS (Postfix)
  [entryPoints.smtp]
    address = ":587"

  # TCP para IMAPS (Dovecot)
  [entryPoints.imaps]
    address = ":993"

[log]
  level = "WARN"

[accessLog]

[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addServicesLabels = true
    addRoutersLabels = true

[api]
  dashboard = true

[providers.docker]
  watch = true
  exposedByDefault = false
  network = "keiko_network"

[providers.file]
  filename = "/traefik_dynamic.toml"
