services:
  grafana:
    image: grafana/grafana:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.infra.local`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=keiko_network"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - keiko_network

volumes:
  grafana_data:

networks:
  keiko_network:
    external: true